### ISSUE TITLE
multiple buckets (users) with different ARQ_ENCRYPTION_PASSWORD for each throws "restore error: decrypt error: bad decrypt" 

### ISSUE THREAD

**Issue by allanzoid** [arqbackup/arq_restore#10]
I use a single AWS account with multiple users/keys to store backups in each computer's bucket.  Each user has their own ACCESS_KEY  SECRET_KEY and ENCRYPTION_PASSWORD.

When I use the arq_restore, I can get only one user's data (the first bucket handed back from AWS) if I chose the correct key and password combos.  Other buckets are not accessible because arq_restore stops when it hits the error "restore error: decrypt error: bad decrypt".

Maybe it should continue to look for additional buckets if the decrypt fails, or be able to pick the bucket by name from a list if you have provided the right keys.

Thanks!  I like the software, love the idea of open source the restore too.

**Comment by arqbackup** [comment]
The latest version of arq_restore has a feature for adding multiple targets, which should resolve this.
