### ISSUE TITLE
crossplattform

### ISSUE THREAD

**Issue by tristan-k** [arqbackup/arq_restore#16]
Please make arq_restore available for other operating systems like Linux and FreeBSD or even Windows. In the past I found myself in situation where I did have no access to mac os x but wanted to recover some files from my backup server. I would really appreciate that move.

**Comment by wincent** [comment]
I am not sure how up-to-date this is with respect to the latest protocol changes or newer backup targets (Google Drive etc), but there is a Go package that will work on any platform here:

http://godoc.org/code.google.com/p/rsc/arq

**Comment by arqbackup** [comment]
Sorry for taking so very long to reply to this.
Arq is now available for both Mac and Windows. We don't plan to rewrite it to work on Linux though.
