### ISSUE TITLE
missing support for AWS region eu-central-1

### ISSUE THREAD

**Issue by mroi** [arqbackup/arq_restore#24]
The new Amazon region in central Europe `eu-central-1` is not supported. Querying backups stored there results in `(null)` outputs. I tried adding the region myself to `cocoastack/aws/AWSRegion.m`, but apparently, support for a new authentication method `AWS4-HMAC-SHA256` is required to support this region.

**Comment by JohanSpaedtke** [comment]
+1

**Comment by arqbackup** [comment]
Sorry for taking so long to reply.
We just updated the code to work with all Arq 5 backups, in all AWS regions.
