### ISSUE TITLE
DropBox support

### ISSUE THREAD

**Issue by wincent** [arqbackup/arq_restore#27]
Any plans to add support for restoring from DropBox?

**Comment by neilsmith** [comment]
+1 - this would be very useful

**Comment by aweiler** [comment]
+1

**Comment by arqbackup** [comment]
Sorry for taking so long to reply to this.
We're not planning to add Dropbox. We can't publish our Dropbox API keys. To restore from a Dropbox backup set, copy the backup set to a local disk and restore from that.
