### ISSUE TITLE
OneDrive support

### ISSUE THREAD

**Issue by anttivs** [arqbackup/arq_restore#28]
OneDrive support seems to be missing from the command-line tool.

**Comment by csu** [comment]
Seconding this.

**Comment by nmatthews** [comment]
A third vote for this.

**Comment by sreitshamer** [comment]
It's coming soon! Sorry for the delay.

**Comment by johnstok** [comment]
+1

**Comment by arqbackup** [comment]
Sorry for taking so long to reply to this.
We're not planning to add OneDrive. We can't publish our OneDrive API keys. To restore from a OneDrive backup set, copy the backup set to a local disk and restore from that.
