### ISSUE TITLE
Missing versioning scheme

### ISSUE THREAD

**Issue by singingwolfboy** [arqbackup/arq_restore#3]
I've packaged arq_restore for Macports: http://trac.macports.org/browser/trunk/dports/sysutils/arq_restore/Portfile However, package management systems use version numbers to keep track of when software is out of date. It would be very useful if there were some sort of versioning scheme for arq_restore, so that you could indicate the scope of changes: [Generally](http://en.wikipedia.org/wiki/Software_versioning), the major number is increased when there are significant jumps in functionality, the minor number is incremented when only minor features or significant fixes have been added, and the revision number is incremented when minor bugs are fixed. For Macports, I've set this project at version 0.0.1, but you can set whatever version you want and I'll just try to track it in the Portfile.

**Comment by arqbackup** [comment]
Closing this because that project is no longer being maintained.
