### ISSUE TITLE
Amazon Cloud Drive Support

### ISSUE THREAD

**Issue by crypticgeek** [arqbackup/arq_restore#30]
This tool needs support / instructions for Amazon Cloud Drive.

**Comment by romusz** [comment]
pretty please.

**Comment by emmekappa** [comment]
+1

**Comment by stuartisaac** [comment]
Ditto

**Comment by romusz** [comment]
without the support for Amazon Cloud Drive it's an abandoned project, as far I am concerned - i'm reluctant do upgrade to v5 (paid) if i cannot restore my backups with an open-source tool. Please consider that viable open-source projects start popping up. I'd gladly update to v5 the this tool will be brought up to date with the storage backend of my choice (ACD).

**Comment by sreitshamer** [comment]
Sorry! Working on it.

**Comment by mgraham-cracker** [comment]
+1 the request for ability to command-line restore Amazon Cloud Drive backups. I need to automate the restore of backups to a secondary location daily. I would prefer not to have to move my backups to S3 if possible, since my backups are already on the Cloud Drive.

**Comment by arqbackup** [comment]
Sorry for taking so long to reply to this.
We're not planning to add Amazon Drive. We can't publish our Amazon Drive API keys. To restore from a Amazon Drive backup set, copy the backup set to a local disk and restore from that.
