### ISSUE TITLE
Using `arq_restore googlecloudstorage`

### ISSUE THREAD

**Issue by alanthing** [arqbackup/arq_restore#31]
It might be worth noting somewhere that you need to enable the "Interoperability API" within Google Cloud Storage to get an AWS-like keypair in order to access `arq_restore googlecloudstorage` properly. Once you do, your command will look very similar to AWS:

```
$ arq_restore listcomputers googlecloudstorage GOOGPABC123DEF456GHI "g0uU0r3G4da+kr8Aa4fRCm5iWJz8UNElCuOGSP" arq-bucketname
```

An explanation can be found at https://cloud.google.com/storage/docs/migrating#keys

**Comment by fab1an** [comment]
This does not work in the current version of arq_restore.
