### ISSUE TITLE
Feature: restore individual files or subfolders from a folder

### ISSUE THREAD

**Issue by philipmw** [arqbackup/arq_restore#37]
I used Arq to back up a folder with thousands of files totaling many gigabytes in size. I want to restore just a small portion of it, but the command-line tool does not support that.

**Comment by arqbackup** [comment]
Actually it does support that. The last parameter of the "restore" command is optional -- give the relative path within the folder and it'll only restore that subset.

**Comment by arqbackup** [comment]
Could you please provide the command you used to produce the output in your gist?

**Comment by arqbackup** [comment]
Which gist?

**Comment by philipmw** [comment]
You are not talking to me, are you? I am not sure what gist you are referring to.

**Comment by arqbackup** [comment]
Sorry! Clicked the wrong item.

**Comment by philipmw** [comment]
The existence of this feature is hidden - I looked both on the tool's web site and the help output, and did not see it. Can you document this feature better?

**Comment by arqbackup** [comment]
Thanks for pointing that out. I added it to the web page: https://arqbackup.github.io/arq_restore/

**Comment by philipmw** [comment]
Perfect, thanks!
