### ISSUE TITLE
Cannot pass encryption password via standard input using java.lang.Process

### ISSUE THREAD

**Issue by johnspurlock** [arqbackup/arq_restore#41]
arq_restore commands that require the encryption password prompt for the password using standard input do not work properly when calling from java.lang.Process and passing standard input in the usual way [1].

Getting: "arq_restore: Inappropriate ioctl for device"

If passing via standard input cannot be done, perhaps allow passing the password via an environment or optional command arg as a fallback?  Standard input would be preferred from a security point of view.

Thanks!

Mac OS 10.12.6
Java 1.8.0_121-b13
arq_restore sha1 251875ef30e55943a3c9406a1e7e2a1da32ae8f9  (no version command?)

[1] https://docs.oracle.com/javase/8/docs/api/java/lang/Process.html#getOutputStream--

**Comment by arqbackup** [comment]
That's because arq_restore calls tcsetattr() to disable echo before it prompts for the password -- see [ArqRestoreCommand readPasswordWithPrompt:error:]. 
It only works from a terminal.
