### ISSUE TITLE
Please document object sha1 computation for encryption v3

### ISSUE THREAD

**Issue by johnspurlock** [arqbackup/arq_restore#42]
It sounds like using a secret to compute the sha1 used for large object file names is a relatively recent change.  The file format documentation [1] says "the third key is concatenated with file data to calculate a SHA1 identifier" but does not provide the formula.

Can you be more specific on this?  I tried sha1(key3 + file bytes) and some other combos on a file [2] in a newly-created local disk-based repo and I can't get it to match the filename hash.

I'm fairly sure I have the right key3, since the decryption process is working properly (with key1), and the initial hmac check passed on the entire master keys data.

Thanks,
John

[1] https://www.arqbackup.com/arq_data_format.txt
[2] e.g. `<target dir>/<computer uuid>/objects/xx/xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx`

**Comment by johnspurlock** [comment]
Ah, I think I got it.  It's sha1(key3 + decrypted and decompressed file bytes), not the raw file bytes.  Still might make sense to update the format doc to be more explicit.

**Comment by arqbackup** [comment]
Yes, that's correct. The data format document describes it in the second paragraph:

> (It's not quite that simple actually. To make the names less susceptible to
> lookup tables, Arq actually calculates the SHA1 hash of the third encryption
> key (see "Encryption Dat File" below) concatenated with the blob's data. We'll
> use "SHA1" as shorthand throughout this document for this identifier.)
