### ISSUE TITLE
The authorization header is malformed; Invalid credential date. Date is not the same as X-Amz-Date

### ISSUE THREAD

**Issue by mgadda** [arqbackup/arq_restore#48]
The binary version of arq_restore _and_ latest master fail immediately with the error:

```
arq_restore: GET https://s3.amazonaws.com/: The authorization header is malformed; Invalid credential date. Date is not the same as X-Amz-Date.
```

**Comment by arqbackup** [comment]
What arguments did you give to arq_restore?
What version of macOS are you using?

**Comment by mgadda** [comment]
Apologies for the poor details. This is reproducible for me on both the last version of Catalina 10.15.7 and on Big Sur 11.0.1. I ran the command: `./arq_restore list computers aws_s3`, where `aws_s3` is an arbitrary target name. 

However, I just deleted the target and re-added it and surprise, now it's working. So it's going to be difficult to reproduce without more specific knowledge of the conditions that could ever lead to such behavior. Feel free to close this ticket as desired.

**Comment by arqbackup** [comment]
-- Please reply above this line --


Hello,

We received your email. We'll get back to you as soon as possible. We
strive to answer emails within 1 business day.

Arq Backup
support@arqbackup.com

**Comment by arqbackup** [comment]
Hmm. OK. Wish I knew how to reproduce it.

**Comment by sethfitz** [comment]
Setting `TZ=UTC` fixes/works around this, suggesting that the timestamp used in the signature uses local time without converting it to UTC. Depending on S3 validation behavior, this could mean that it doesn't work during the window where UTC has flipped to the next day, but local time is still the current day (which would explain the apparent intermittent nature).
